# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  devicemanagement:
    image: devicemanagement
    build:
      context: .
      dockerfile: ./Dockerfile

    restart: unless-stopped
    ports:
      - 5001:8080
    env_file:
      - ./app.secrets.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

